project_name: mobidata-poller

before:
  hooks:
    - go mod tidy

builds:
  - id: poller
    main: ./cmd/poller
    binary: poller
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: server
    main: ./cmd/server
    binary: server
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    builds:
      - poller
      - server
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: PatrickSteil
    name: mobidata-poller

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
