version: 2

project_name: mobidata-poller

before:
  hooks:
    - go mod tidy

builds:
  - id: poller
    main: ./cmd/poller
    binary: poller
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: server
    main: ./cmd/server
    binary: server
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: poller
    ids:
      - poller
    name_template: "{{ .ProjectName }}_poller_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

  - id: server
    ids:
      - server
    name_template: "{{ .ProjectName }}_server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: checksums.txt

release:
  github:
    owner: PatrickSteil
    name: mobidata-poller
  name_template: "v{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
